name: CD

on:
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: ./bin/*.apk
          retention-days: 30
